// Exports contract ABIs (and creation bytecode, for local/E2E deployments) from the Foundry build output
// into packages/chain as typed modules. Run after `pnpm contracts:build`: pnpm contracts:export-abi
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "packages/chain/src/abis");
mkdirSync(outDir, { recursive: true });

const contracts = [
  ["ClearGatewaySplitter", "clearGatewaySplitterAbi", "clearGatewaySplitterBytecode"],
  ["MockUSDC", "mockUsdcAbi", "mockUsdcBytecode"],
  ["DepositFactory", "depositFactoryAbi", "depositFactoryBytecode"],
  ["DepositForwarder", "depositForwarderAbi", "depositForwarderBytecode"],
];

for (const [name, abiName, bytecodeName] of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, `contracts/out/${name}.sol/${name}.json`), "utf8"));
  const body =
    `// GENERATED by scripts/export-abi.mjs from contracts/out. Do not edit.\n` +
    `export const ${abiName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n\n` +
    `/** Creation bytecode. Used for local Anvil / E2E deployments only; production deploys via Foundry scripts. */\n` +
    `export const ${bytecodeName} = "${artifact.bytecode.object}" as const;\n`;
  writeFileSync(join(outDir, `${name}.ts`), body);
  console.log(`exported ${name} (${artifact.abi.length} ABI entries, ${(artifact.bytecode.object.length - 2) / 2} bytes)`);
}
